### ISSUE TITLE
播放中有时停止并报错

### ISSUE THREAD

**Issue by mundoque** [zhkrb/Iwara-android-client#1]
提示「错误码: -10000」

**Comment by zhkrb** [comment]
当再次出现的时候希望能点击右上角的分享按钮，复制视频链接。

因为目前ui逻辑的问题，可能需要快速点击才能确保正确点击到分享按钮

**Comment by mundoque** [comment]
换了网络环境之后播放同样的视频也没再出现，推测可能是网络问题

**Comment by zhkrb** [comment]
emmm，主要是如果ijkplayer报错的话，就一定是-10000，但错误有可能是各种各样的，就很头疼。还是等后面再想办法优化吧
