### ISSUE TITLE
关于如何解析出视频的直链

### ISSUE THREAD

**Issue by Xiue233** [zhkrb/Iwara-android-client#4]
很感谢大佬分享的源码，我也想写个软件，但是发现自己通过OKHttp获取到的视频详情页的HTML源码中，没有关于直链的信息。

应该是靠js来动态设置的(原始源码中有"Video is processing"的显示)，但是，令我好奇的是为什么您的请求可以获取到视频直链？

还请赐教。

**Comment by Xiue233** [comment]
![Uploading image.png…]()

**Comment by zhkrb** [comment]
图挂了

视频列表中跳转Url格式为 `https://host/videos/VideoId`, 通过VideoId可以用 `https://Host/api/video/VideoId`获取视频链接, 解析格式为

```
[
    {
        "resolution": "清晰度",
        "uri": "链接",
        "mime": "资源格式"
    }
]
```

注意链接是有时间hash校验的, 一旦播放失败，需要重新获取新的播放链接

**Comment by Xiue233** [comment]
非常感谢
