### ISSUE TITLE
关于如何解析出显示全部简介

### ISSUE THREAD

**Issue by FutoTan** [zhkrb/Iwara-android-client#6]
rt，我也正在做 [iwara的客户端](https://github.com/Tao0Lu/Iwara)  ~~(造轮子~~，估计之后会用 flutter 重写支持全平台），碰巧看到了dalao的源码。但是我在解析视频界面时，发现需要点击 `<a href="..#">show all `的按钮才能显示全部内容，然后抓包抓到死都没有看到像 `/api/video/`的东西（（（，还有请问如何用 DoH 来观看 iwara 全年龄站的 Youtube 视频。

**Comment by zhkrb** [comment]
直接读取原始document，里面`div.field-item`是完整的，你在打开的页面上使用控制台看到是已经渲染后的element，直接右键查看源代码

目前对dns污染以及gfw阻断都没有处理。本身来说，都上I站了再不会翻墙，说不过去

**Comment by FutoTan** [comment]
> 直接读取原始document，里面`div.field-item`是完整的，你在打开的页面上使用控制台看到是已经渲染后的element，直接右键查看源代码
> 
> 目前对dns污染以及gfw阻断都没有处理。本身来说，都上I站了再不会翻墙，说不过去

听您怎么说，我才发现原来我已经实现了这个功能（。只不过我一直在想这个问题，没发现已经可以了（（（
